minimal:
  foo: 
    - runs-on: ubuntu-24.04
      container: ""
      hostcxx: "gcc-14"
  python:
    "3.9"

quick:
  foo:
    - runs-on: ubuntu-24.04
      container: ""
      hostcxx: "gcc-14"
    - runs-on: windows-2025
      container: ""
      hostcxx: "Visual Studio 17 2022"
  python:
    - "3.9"

full:
  foo:
    - runs-on: ubuntu-24.04
      container: ""
      hostcxx: "gcc-14"
    - runs-on: windows-2025
      container: ""
      hostcxx: "Visual Studio 17 2022"
    - runs-on: ubuntu-24.04
      container: "quay.io/pypa/manylinux_2_28_x86_64"
      hostcxx: "gcc-toolset-12"
  python:
    - "3.9"
    - "3.10"
