name: dynamic

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.output-matrix.outputs.matrix}}
    steps:
      - uses: actions/checkout@v4
      - name: Output Matrix
        id: output-matrix
        run: |
          MATRIX_YML=".github/matrices.yaml"
          if [[ "${{ github.event_name}}" == "workflow_dispatch" ]]; then
            matrix=$(yq -o j -I 0 '.full' "$MATRIX_YML")
          else
            matrix=$(yq -o j -I 0 '.quick' "$MATRIX_YML")
          fi
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"
  execute:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: print
        run: | 
          # echo "os=${{ matrix.os }}"
          # echo "python=${{ matrix.python }}"
