name: dynamic

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

jobs:
  # Select the CI matrix for the full job
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.output-matrix.outputs.matrix}}
    env:
      # the choice of matrix, initialsed to the quick default
      SELECTED_MATRIX: "quick"
    steps:
      - uses: actions/checkout@v4
      # Choose the full matrix if the workflow was triggered by a workflow dispatch, push to main, or PR with the ci-full label
      - name: Select full matrix
        if: |
          (github.event_name == 'workflow_dispatch') || 
          (github.event_name == 'push' && github.ref == 'refs/heads/main' ) ||
          (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ci-full'))
        run: |
          echo "SELECTED_MATRIX=full" >> $GITHUB_ENV

      # Output the selected matrix for subsequent steps
      - name: Output Matrix
        id: output-matrix
        run: |
          MATRIX_YML=".github/matrices.yaml"
          matrix=$(yq -o j -I 0 ".${SELECTED_MATRIX}" "$MATRIX_YML")
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
  # Execute the actual job, with the dynamically selected matrix, as long as the workflow was not triggered by a pull request labelling event which did not add a "ci-" label
  execute:
    runs-on: ubuntu-latest
    if: |
      (github.event_name != 'pull_request') ||
      (github.event_name == 'pull_request' && github.event.action != 'labeled') ||
      (github.event_name == 'pull_request' && github.event.action == 'labeled' && startsWith(github.event.label.name, 'ci-'))
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: print
        run: | 
          echo "os=${{ matrix.os }}"
          echo "python=${{ matrix.python }}"
